@startuml　git-command-cheat-sheet

skinparam participantPadding 40
skinparam BoxPadding 30

actor developer as developer
box "local" #LightBlue
participant  "master or main" as lmaster
participant  featureA as lfeatureA
end box

box "remote" #PaleGreen
participant  "master or main"  as rmaster
participant  featureA as rfeatureA
end box

== リポジトリ作成 ==
alt リポジトリが存在している
developer <- rmaster : git clone [URL]
else 存在していない
developer -> lmaster : git init
lmaster -> lmaster : git add .
lmaster -> lmaster : git commit -m "First commit"
lmaster -> lmaster : git remote add origin remote [URL]
lmaster -> rmaster : git push origin [master]
end

== [featureA]ブランチを[master]から作成 ==
lmaster -> lfeatureA : git branch [featureA] [master]

== [featureA]ブランチへ移動 ==
lmaster -> lfeatureA : git checkout [featureA]
opt gitのバージョンが[2.23.0]以上の場合switchが利用可能 
lmaster -> lfeatureA : git switch -c [featureA]
end

== ステージング ==
lfeatureA -> lfeatureA : git add [file]
opt ステージから外す
lfeatureA -> lfeatureA : git reset [file]
end

== 編集を一時退避 ==
lfeatureA -> lfeatureA : git stash
opt 元に戻す
lfeatureA -> lfeatureA : git stash pop
else 退避一覧を表示
lfeatureA -> lfeatureA : git stash list
else 退避を削除
lfeatureA -> lfeatureA : git stash clear
end

== 編集差分の確認 ==
lfeatureA -> lfeatureA : git diff

== コミット ==
lfeatureA -> lfeatureA : git commit -a -m "[comment]"

== [featureA]ブランチをremoteへ送信 ==
lfeatureA -> rfeatureA : git push origin [featureA]

== [featureA]ブランチを[master]へマージ ==
opt [master]ブランチでなければ移動
lmaster <- lfeatureA : git checkout [master]
end
lmaster -> lmaster : git merge [featureA]
lmaster -> rmaster : git push origin [master]
opt マージを取り消す
lmaster -> lmaster : git merge --abort
end 

== remotoの履歴を取得 ==
lmaster <- rmaster : git fetch origin [master]
lmaster -> lmaster : git merge origin/[master]
opt fetchとmergeを同時に行う
lmaster <- rmaster : git pull origin [master]
end

== タグの作成 ==
lmaster -> lmaster : git tag -a [v1.0] -m "[comment]"
lmaster -> rmaster : git push origin [v1.0]
opt 一覧表示
lmaster -> lmaster : git tag
end

== [master]のファイル名の変更 ==
opt [master]ブランチでなければ移動
lmaster <- lfeatureA : git checkout [master]
end
lmaster -> lmaster : git mv [oldname] [newname]
lmaster -> lmaster :git commit -a -m "[comment]"
lmaster -> rmaster :git push origin [master]

== [featureA]ブランチを削除 ==
lmaster -> lfeatureA : git branch -d [featureA]
lmaster -> rfeatureA : git push --delete origin [featureA]

@enduml