name: generate plantuml
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: plantuml
      id: plantuml
      uses: grassedge/generate-plantuml-action@v1.5
      with:
        path: docs/svg
        message: "Render PlantUML files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
